-- WhereToWork Initial Schema
-- Run against Supabase PostgreSQL with PostGIS enabled

-- Enable PostGIS
CREATE EXTENSION IF NOT EXISTS postgis;

-- ============================================
-- ENUMS
-- ============================================

CREATE TYPE "image_type" AS ENUM ('logo', 'cover', 'gallery');
CREATE TYPE "seating_size" AS ENUM ('small', 'medium', 'large');
CREATE TYPE "noise_level" AS ENUM ('quiet', 'moderate', 'lively');
CREATE TYPE "busyness_level" AS ENUM ('empty', 'few_people', 'half_full', 'busy', 'packed');

-- ============================================
-- CORE TABLES
-- ============================================

CREATE TABLE "place_categories" (
  "id" INT PRIMARY KEY,
  "category" VARCHAR NOT NULL,
  "description" TEXT,
  "parent_category_id" INT REFERENCES place_categories(id),
  "icon" TEXT
);

CREATE TABLE "places" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" TEXT,
  "category_id" INT REFERENCES place_categories(id),
  "google_maps_url" VARCHAR,
  "google_maps_place_id" VARCHAR,
  "is_verified" BOOL DEFAULT false,
  "is_active" BOOL DEFAULT true,
  "created_at" TIMESTAMP DEFAULT now(),
  "updated_at" TIMESTAMP DEFAULT now()
);

CREATE TABLE "place_locations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place_id" INT REFERENCES places(id) ON DELETE CASCADE,
  "location" GEOGRAPHY(POINT, 4326),
  "address" VARCHAR,
  "area" VARCHAR,
  "postcode" VARCHAR,
  "is_primary" BOOL DEFAULT true
);

-- ============================================
-- REMOTE WORKER SPECIFIC
-- ============================================

CREATE TABLE "workspace_details" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place_id" INT UNIQUE REFERENCES places(id) ON DELETE CASCADE,

  -- Pricing
  "coffee_price_gbp" DECIMAL(5,2),
  "min_spend_gbp" DECIMAL(5,2),
  "has_free_option" BOOL DEFAULT false,

  -- Stay duration
  "typical_stay_mins" INT,
  "max_stay_mins" INT,
  "stay_notes" TEXT,

  -- Facilities
  "has_wifi" BOOL DEFAULT true,
  "wifi_speed_mbps" INT,
  "wifi_reliable" BOOL,
  "has_plugs" BOOL,
  "plug_quantity" VARCHAR,

  -- Atmosphere
  "seating_size" seating_size,
  "noise_level" noise_level,
  "has_outdoor_seating" BOOL DEFAULT false,
  "has_standing_desks" BOOL DEFAULT false,
  "has_meeting_rooms" BOOL DEFAULT false,

  -- Busyness patterns (free-form for now)
  "busyness_notes" TEXT,
  "best_times" TEXT,
  "peak_times" TEXT,

  -- Toilets, food
  "has_toilets" BOOL DEFAULT true,
  "has_food" BOOL,
  "food_notes" TEXT,

  -- Overall
  "laptop_friendly_score" INT CHECK (laptop_friendly_score >= 1 AND laptop_friendly_score <= 5),
  "notes" TEXT,

  "updated_at" TIMESTAMP DEFAULT now()
);

-- ============================================
-- OPENING HOURS
-- ============================================

CREATE TABLE "place_opening_hours" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place_id" INT REFERENCES places(id) ON DELETE CASCADE,
  "day_of_week" INT NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  "open_time" TIME,
  "close_time" TIME,
  "is_closed" BOOL DEFAULT false,
  UNIQUE(place_id, day_of_week)
);

COMMENT ON COLUMN "place_opening_hours"."day_of_week" IS '0=Mon, 1=Tue, ..., 6=Sun';

-- ============================================
-- WEB & SOCIAL LINKS
-- ============================================

CREATE TABLE "place_web_links" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place_id" INT UNIQUE REFERENCES places(id) ON DELETE CASCADE,
  "website_url" VARCHAR,
  "instagram_url" VARCHAR,
  "x_url" VARCHAR,
  "facebook_url" VARCHAR,
  "tiktok_url" VARCHAR
);

-- ============================================
-- IMAGES
-- ============================================

CREATE TABLE "place_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place_id" INT REFERENCES places(id) ON DELETE CASCADE,
  "image_type" image_type,
  "image_index" INT DEFAULT 0,
  "url" VARCHAR NOT NULL
);

-- ============================================
-- REVIEWS (community contributed)
-- ============================================

CREATE TABLE "place_reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place_id" INT REFERENCES places(id) ON DELETE CASCADE,
  "reviewer_name" VARCHAR DEFAULT 'Anonymous',
  "score" INT CHECK (score >= 1 AND score <= 5),
  "review_text" TEXT,
  "created_at" TIMESTAMP DEFAULT now()
);

-- ============================================
-- BUSYNESS REPORTS (crowdsourced)
-- ============================================

CREATE TABLE "busyness_reports" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place_id" INT REFERENCES places(id) ON DELETE CASCADE,
  "busyness_level" busyness_level NOT NULL,
  "day_of_week" INT CHECK (day_of_week >= 0 AND day_of_week <= 6),
  "time_of_day" TIME,
  "reported_at" TIMESTAMP DEFAULT now()
);

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX idx_place_locations_geo ON place_locations USING GIST (location);
CREATE INDEX idx_places_category ON places(category_id);
CREATE INDEX idx_places_active ON places(is_active) WHERE is_active = true;
CREATE INDEX idx_workspace_details_place ON workspace_details(place_id);
CREATE INDEX idx_place_opening_hours_place ON place_opening_hours(place_id);

-- ============================================
-- SEED CATEGORIES
-- ============================================

INSERT INTO place_categories (id, category, description, icon) VALUES
(1, 'Cafe', 'Coffee shops and cafes', 'coffee'),
(2, 'Co-working Space', 'Dedicated co-working spaces', 'building'),
(3, 'Library', 'Public and private libraries', 'book'),
(4, 'Hotel Lobby', 'Hotel lobbies open to public', 'hotel'),
(5, 'Restaurant', 'Restaurants with work-friendly vibes', 'utensils'),
(6, 'Pub', 'Pubs with daytime work-friendly atmosphere', 'beer'),
(7, 'Bookshop Cafe', 'Bookshops with cafe areas', 'book-open'),
(8, 'Other', 'Other work-friendly locations', 'map-pin');
